# Alexandre Theophile Vandermonde Matrix
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [23]:
import numpy as np

def vand_mat(ip_vector, increasing=False):
    N=ip_vector.size
    if increasing == False:
        op_matrix=np.array([x**(N-i-1) for x in ip_vector for i in range(N)]).reshape(N,N)
    elif increasing == True:
        op_matrix=np.array([x**i for x in ip_vector for i in range(N)]).reshape(N,N)
    return op_matrix

# the function will return a matrix of N by N, where N is the total number of elements in input vector
ip_vector= np.array([1,2,3,4,])
print("The input vecto is :", ip_vector, "\n")
print("The size of input vector (N) is :", ip_vector.size, '\n')
print("The Vandermonde Matrix when increasing is True : \n\n",vand_mat(ip_vector, True), "\n")
print("The Vandermonde Matrix when increasing is False : \n\n",vand_mat(ip_vector, False))

The input vecto is : [1 2 3 4] 

The size of input vector (N) is : 4 

The Vandermonde Matrix when increasing is True : 

 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]] 

The Vandermonde Matrix when increasing is False : 

 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [25]:
# Another approach using column_stack instead of reshaape function
def vand_mat(ip_vector, increasing=False):
    N=ip_vector.size
    x=ip_vector
    if increasing== False:
        op_matrix=np.column_stack([x**(N-i-1) for i in range(N)])
    elif increasing == True:
        op_matrix=np.column_stack([x**i for i in range(N)])
    return op_matrix

ip_vector= np.array([1,2,3,5])
print("The input vecto is :", ip_vector, "\n")
print("The size of input vector (N) is :", ip_vector.size, '\n')
print("The Vandermonde Matrix when increasing is False : \n\n",vand_mat(ip_vector, False), "\n")
print("The Vandermonde Matrix when increasing is True : \n\n",vand_mat(ip_vector, True))

The input vecto is : [1 2 3 5] 

The size of input vector (N) is : 4 

The Vandermonde Matrix when increasing is False : 

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]] 

The Vandermonde Matrix when increasing is True : 

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


# Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [47]:
def moving_average(n,k=3):
    csum=np.cumsum(n)
    csum[k:]=csum[k:]-csum[:-k]
    return csum[k-1:]/k

n=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print("The test array is :", n, '\n')
op_array=np.array(moving_average(n, k=3)).round(2)
print("The output array consisting of moving average when window value is 3 is :\n", op_array)

The test array is : [  3   5   7   2   8  10  11  65  72  81  99 100 150] 

The output array consisting of moving average when window value is 3 is :
 [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
